# Configuration values are to be set to true or false.
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Play sounds on commands?
sounds: true

# Can violent commands cause a minor amount of damage?
violent-commands-damage: true

# Does /murder kill players?
Murder-Command-Kills-Player: false

# Should feelings be broadcasted to everyone instead of between players?
global-feelings: false

# If a player does /cf reload should the CONSOLE be notified.
reload-notify-console: true

# Shows more detailed command usage help information.
extra-help: true

# Can we notify you if we find an update?
Update-Notify: true

# Can we notify you if we find an update?
Cooldown-Delay-Seconds: 3

# If the owner of chatFeelings logs on to your server can he see the ChatFeelings version?
Developer-Join: true

# Enable other effects like potions and overlays?
other-effects: true

# Show particles on feeling commands?
particles: true

# Shows stack trace errors. Only enable if you need it or you're reporting a bug
debug: false

# Please leave this on, it's to help me make a better ChatFeelings! :)
Metrics: true

# Don't touch please ;)
config-version: 4
