name: ChatFeelings
main: com.zach_attack.chatfeelings.Main
website: https://www.spigotmc.org/resources/chatfeelings.12987/
author: zach_attack
version: 3.7.3-BETA
api-version: 1.13
description: ChatFeelings lets you show your affection to players!
commands:
  hug:
    description: Gives somebody a nice warm hug!
  slap:
    description: Gives someone a piece of your mind!
  poke:
    description: Poke someone to get their attention!
  highfive:
    description: Show your support, and highfive a player!
  facepalm:
    description: Facepalm at what a player has said!
  yell:
    description: Yells at a player as loud as you can!
  chatfeelings:
    description: General command for chatfeelings.
  cf:
    description: General command for chatfeelings.
  feelings:
    description: Lists all the feelings you can do!
    aliases: emotions
  bite:
    description: Bites a player right on the arm.
  snuggle:
    description: Snuggles a player with warm hugs.
  shake:
    description: Shakes a player to their feet.
  stab:
    description: Stabs a player... ouch!
  kiss:
    description: Make sweet sweet love.
  punch:
    description: Punch the lights out of a player.
  murder:
    description: Murder someone...
  boi:
    description: Here comes dat boi. How dank.
  cry:
    description: Cry at a player, how sad.
  dab:
    description: Cash me outside. How bout dab?
  lick:
    description: Lick someone like an ice-cream sundae!
  scorn:
    description: Shame a player for what they've done.
  pat:
    description: Pat a players head for being a good boy... or girl.
  stalk:
    description: Stalk a player carefully... carefully.
  spook:
    description: Spook a player out of their socks!