General:
  Global-Feelings:
    Enabled: false
    Broadcast-To-Console: true
  Prevent-Self-Feelings: true
  Violent-Command-Harm: true
  No-Violent-Cmds-When-Sleeping: true
  Cooldowns:
    Feelings:
      Enabled: true
      Seconds: 10
    Ignoring:
      Enabled: true
      Seconds: 5
  Particles: true
  Extra-Help: true
  Disabled-Sending-Worlds: []
  Disabled-Receiving-Worlds:
  - world_the_end
Other:
  Bypass-Version-Block: false
  Vanished-Players:
    Check: true
    Use-Legacy: false
  Player-Files:
    Cleanup: true
    Cleanup-After-Days: 185
  Updates:
    Check: true
  Metrics: true
  Debug: false
Version: 2